#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
# Gradle start up script for POSIX generated by Gradle.
#
# Optional ENV vars:
# ------------------
# GRADLE_OPTS - JVM options for Gradle, e.g. "-XX:MaxMetaspaceSize=256m"
# GRADLE_HOME - location of a Gradle installation
# GRADLE_USER_HOME - location of gradle user directory defaults to ~/.gradle
# JAVA_HOME - location of a JDK home dir
#

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=$(dirname "$0")
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    case $link in             #(
      /*)   app_path="$link" ;; #(
      *)    app_path="$APP_HOME/$link" ;;
    esac
done

# Change from hard link to canonical path.
APP_HOME=$(cd "$APP_HOME" && pwd -P)

# Call the command
exec java \
    -Xmx64m -Xms64m \
    -Dorg.gradle.appname="gradlew" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"